In [2]:
import pandas as pd
import tensorflow as tf
import numpy as np

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [30]:
DATAPATH = './data/games.csv'

In [31]:
games = pd.read_csv(DATAPATH)

In [32]:
games.dtypes

Unnamed: 0             int64
SEASON_ID              int64
TEAM_ID                int64
TEAM_ABBREVIATION     object
TEAM_NAME             object
GAME_ID                int64
GAME_DATE             object
MATCHUP               object
WL                    object
MIN                    int64
PTS                    int64
FGM                    int64
FGA                    int64
FG_PCT               float64
FG3M                   int64
FG3A                   int64
FG3_PCT              float64
FTM                    int64
FTA                    int64
FT_PCT               float64
OREB                   int64
DREB                   int64
REB                    int64
AST                    int64
STL                    int64
BLK                    int64
TOV                    int64
PF                     int64
PLUS_MINUS           float64
dtype: object

In [33]:
games = games.drop(['Unnamed: 0'], axis=1)

In [34]:
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22019,1610612748,MIA,Miami Heat,21900970,2020-03-11,MIA vs. CHA,L,239,98,...,0.833,9,27,36,32,8,5,14,17,-13.0
1,22019,1610612743,DEN,Denver Nuggets,21900973,2020-03-11,DEN @ DAL,L,240,97,...,0.625,3,37,40,23,6,4,15,20,-7.8
2,22019,1610612752,NYK,New York Knicks,21900969,2020-03-11,NYK @ ATL,W,264,136,...,0.735,6,41,47,32,14,9,12,23,0.0
3,22019,1610612742,DAL,Dallas Mavericks,21900973,2020-03-11,DAL vs. DEN,W,240,113,...,0.739,13,39,52,23,9,2,10,14,8.0
4,22019,1610612765,DET,Detroit Pistons,21900971,2020-03-11,DET @ PHI,L,241,106,...,0.680,6,26,32,25,10,3,8,24,-14.2

In [35]:
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
    dataframe = dataframe.copy()
    labels = dataframe.pop('WL')
    ds = tf.data.Dataset.from_tensor_slices((dataframe.values, labels.values))
    if shuffle:
        ds = ds.shuffle(buffer_size = len(dataframe))
    ds = ds.batch(batch_size)
    return ds

In [36]:
games.pop('SEASON_ID')
games.pop('TEAM_ID')
games.pop('GAME_ID')
games.pop('TEAM_ABBREVIATION')

0        MIA
1        DEN
2        NYK
3        DAL
4        DET
        ...
29995    BOS
29996    LAL
29997    ATL
29998    DAL
29999    DEN
Name: TEAM_ABBREVIATION, Length: 30000, dtype: object

In [37]:
feature_columns = []
obj_columns = ['TEAM_NAME', 'GAME_DATE', 'MATCHUP', 'WL']
#numeric columns
for i in obj_columns:
    games[i] = pd.Categorical(games[i])
    games[i] = games[i].cat.codes 
for header in games.columns:
    games[header] = games[header].astype('float64')
    if header != 'WL':
        feature_columns.append(feature_column.numeric_column(header))

In [38]:
games.dtypes

TEAM_NAME     float64
GAME_DATE     float64
MATCHUP       float64
WL            float64
MIN           float64
PTS           float64
FGM           float64
FGA           float64
FG_PCT        float64
FG3M          float64
FG3A          float64
FG3_PCT       float64
FTM           float64
FTA           float64
FT_PCT        float64
OREB          float64
DREB          float64
REB           float64
AST           float64
STL           float64
BLK           float64
TOV           float64
PF            float64
PLUS_MINUS    float64
dtype: object

In [60]:
games.head(n=25)

,TEAM_NAME,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42.0,2427.0,1050.0,0.0,239.0,98.0,39.0,84.0,0.464,15.0,...,0.833,9.0,27.0,36.0,32.0,8.0,5.0,14.0,17.0,-13.0
1,22.0,2427.0,465.0,0.0,240.0,97.0,39.0,83.0,0.470,14.0,...,0.625,3.0,37.0,40.0,23.0,6.0,4.0,15.0,20.0,-7.8
2,52.0,2427.0,1395.0,1.0,264.0,136.0,50.0,94.0,0.532,11.0,...,0.735,6.0,41.0,47.0,32.0,14.0,9.0,12.0,23.0,0.0
3,21.0,2427.0,434.0,1.0,240.0,113.0,42.0,92.0,0.457,12.0,...,0.739,13.0,39.0,52.0,23.0,9.0,2.0,10.0,14.0,8.0
4,23.0,2427.0,546.0,0.0,241.0,106.0,39.0,84.0,0.464,11.0,...,0.680,6.0,26.0,32.0,25.0,10.0,3.0,8.0,24.0,-14.2
5,18.0,2427.0,215.0,1.0,239.0,109.0,37.0,82.0,0.451,17.0,...,0.818,15.0,35.0,50.0,20.0,7.0,4.0,14.0,9.0,12.2
6,57.0,2427.0,1642.0,1.0,241.0,124.0,42.0,83.0,0.506,14.0,...,0.813,13.0,37.0,50.0,28.0,7.0,4.0,13.0,18.0,14.0
7,2.0,2427.0,54.0,0.0,265.0,131.0,48.0,106.0,0.453,14.0,...,0.808,15.0,38.0,53.0,26.0,6.0,3.0,17.0,25.0,0.0
8,28.0,2426.0,644.0,0.0,239.0,107.0,37.0,79.0,0.468,11.0,...,0.815,4.0,31.0,35.0,25.0,3.0,0.0,9.0,17.0,-24.0
9,58.0,2426.0,1692.0,0.0,242.0,105.0,35.0,87.0,0.402,11.0,...,0.960,9.0,34.0,43.0,26.0,3.0,5.0,14.0,16.0,-7.2
10,21.0,2426.0,422.0,0.0,240.0,109.0,42.0,92.0,0.457,17.0,...,0.727,7.0,35.0,42.0,23.0,8.0,3.0,14.0,19.0,0.2
11,59.0,2426.0,1791.0,1.0,240.0,121.0,45.0,89.0,0.506,17.0,...,0.824,9.0,37.0,46.0,20.0,9.0,9.0,11.0,17.0,5.6
12,36.0,2426.0,806.0,1.0,242.0,131.0,46.0,92.0,0.500,20.0,...,1.000,11.0,36.0,47.0,28.0,5.0,2.0,10.0,19.0,24.0
13,33.0,2426.0,765.0,0.0,239.0,111.0,46.0,93.0,0.495,9.0,...,0.909,10.0,33.0,43.0,23.0,5.0,8.0,12.0,20.0,-4.4
14,32.0,2426.0,716.0,1.0,241.0,117.0,41.0,80.0,0.513,15.0,...,0.769,5.0,28.0,33.0,24.0,9.0,5.0,16.0,20.0,6.0
15,64.0,2426.0,1907.0,1.0,239.0,119.0,46.0,89.0,0.517,15.0,...,0.800,6.0,34.0,40.0,32.0,11.0,10.0,11.0,15.0,1.2
16,55.0,2426.0,1549.0,1.0,241.0,120.0,43.0,92.0,0.467,14.0,...,0.909,12.0,29.0,41.0,31.0,10.0,3.0,15.0,26.0,5.0
17,12.0,2426.0,146.0,1.0,240.0,114.0,41.0,93.0,0.441,13.0,...,0.864,11.0,35.0,46.0,19.0,9.0,4.0,8.0,15.0,4.4
18,52.0,2426.0,1426.0,0.0,240.0,115.0,42.0,81.0,0.519,8.0,...,0.742,8.0,28.0,36.0,30.0,10.0,3.0,18.0,29.0,-7.0
19,88.0,2426.0,2137.0,1.0,241.0,122.0,35.0,74.0,0.473,14.0,...,0.844,9.0,28.0,37.0,23.0,8.0,4.0,16.0,25.0,7.0
20,20.0,2426.0,330.0,0.0,240.0,103.0,40.0,80.0,0.500,6.0,...,0.739,9.0,26.0,35.0,29.0,9.0,5.0,18.0,15.0,-0.6
21,14.0,2426.0,82.0,1.0,241.0,104.0,37.0,90.0,0.411,13.0,...,0.739,14.0,33.0,47.0,24.0,7.0,3.0,10.0,18.0,3.0
22,38.0,2426.0,897.0,0.0,241.0,102.0,40.0,87.0,0.460,15.0,...,0.583,8.0,38.0,46.0,24.0,7.0,4.0,14.0,22.0,-3.2
23,41.0,2426.0,1006.0,0.0,240.0,115.0,38.0,76.0,0.500,11.0,...,0.737,7.0,32.0,39.0,24.0,7.0,5.0,20.0,22.0,-5.0
24,19.0,2426.0,298.0,1.0,241.0,108.0,42.0,84.0,0.500,12.0,...,0.800,14.0,32.0,46.0,23.0,8.0,6.0,21.0,21.0,0.8

In [40]:
print(feature_columns)

[NumericColumn(key='TEAM_NAME', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='GAME_DATE', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='MATCHUP', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='MIN', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='PTS', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FGM', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FGA', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FG_PCT', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FG3M', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FG3A', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FG3_PCT', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FTM', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FTA', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='FT_PCT', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='OREB', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='DREB', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='REB', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='AST', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='STL', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='BLK', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='TOV', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='PF', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='PLUS_MINUS', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [41]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

In [65]:
train, test = train_test_split(games, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

19200 train examples
4800 validation examples
6000 test examples

In [72]:
batch_size = 128
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

In [73]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(125, activation='relu'),
    tf.keras.layers.Dense(125, activation='relu'),
    tf.keras.layers.Dense(125, activation='relu'),
    tf.keras.layers.Dense(1, activation='relu')
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [74]:
model = get_compiled_model()
model.fit(train_ds, epochs=20)

Epoch 1/20
WARNING:tensorflow:Layer dense_35 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

150/150 [==============================] - ETA: 0s - loss: nan - accuracy: 0.4964  - 0s 2ms/step - loss: nan - accuracy: 0.4966
Epoch 2/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 3/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 4/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 5/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 6/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 7/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 8/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 9/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 10/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 11/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 12/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 13/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 14/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 15/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 16/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 17/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 18/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 19/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020
Epoch 20/20
150/150 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.5020